[package]
name = "TakeOnWeb"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.4"
urlencoding = "2.1"
ureq = "2.5"
tokio = { version = "1.5", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
