[package]
name = "TakeOnWeb"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
image = "0.25.4"
reqwest = { version = "0.11", features = ["blocking"] }
ravif = "0.11"
num_cpus = "1.13"
urlencoding = "2.1"
tiny_http = "0.12"
ureq = "2.5"
